### ISSUE TITLE
Extension is not working for Leetcode Old UI?

### ISSUE THREAD

**Issue by arvinloh** [The-CodingSloth/haha-funny-leetcode-extension#101]
There is an issue with the extension, where even after solving the leetcode problem, it treats it like it isn't solved.
I am using the old version of Leetcode, which may have resulted in this issue. 

https://github.com/The-CodingSloth/haha-funny-leetcode-extension/assets/128887797/ca2de890-d145-41af-a29e-f2362a8fde7b

**Comment by tannnxr** [comment]
Are you able to reproduce this and maybe show any errors that may show up in DevTools please?

**Comment by tannnxr** [comment]
Recommend to close @The-CodingSloth

**Comment by The-CodingSloth** [comment]
Might be a current bug with the public version, not sure if it's there with this newest version since I have to create a website with a privacy page to update the extension now, so I'll work on that soon to update it.
