### ISSUE TITLE
linter file for consistent styling 

### ISSUE THREAD

**Issue by The-CodingSloth** [The-CodingSloth/haha-funny-leetcode-extension#14]
Yeah kinda forgot to add this, it shouldn't take too long

**Comment by Vijaykv5** [comment]
Could you give more on this issue. I would love to work on it

**Comment by The-CodingSloth** [comment]
Yeah, all we need is a prettier/eslint config file to maintain consistent code style/quality. If you need more help let me know 👍

**Comment by kmooredev** [comment]
[Google's TS style guide](https://github.com/google/gts) - just a reference in case we're making a switch to TypeScript soon. I figure we might as well get everything playing nicely together from the jump rather than reconfigure eslint/prettier multiple times.
