### ISSUE TITLE
A way to handle premium problems

### ISSUE THREAD

**Issue by The-CodingSloth** [The-CodingSloth/haha-funny-leetcode-extension#2]
need a way to filter out premium problems for people who don't have LeetCode premium
1. Might have to edit web scraper to check if it's premium (might also change JSON file format to include if isPremium)

**Comment by sanjai0py** [comment]
how to handle the problem if it is premium? should the user be directed to [lintcode](https://www.lintcode.com/)?

**Comment by The-CodingSloth** [comment]
If that problem exists on lintcode, I think that would work perfectly. 
If not we can either filter the problems where isPremium is false and only use those questions.
Another option is in the popup.js/popup.html could have them toggle on/off premium problems.
