### ISSUE TITLE
Migrate to browser extension framework?

### ISSUE THREAD

**Issue by Walter-0** [The-CodingSloth/haha-funny-leetcode-extension#25]
As this project is early in development, would it be worth migrating the logic into this browser extension framework called plasmo? It might be a big lift now but it could save a lot of time in the future.

https://github.com/PlasmoHQ/plasmo

It would automatically take care of https://github.com/The-CodingSloth/haha-funny-leetcode-extension/issues/9, https://github.com/The-CodingSloth/haha-funny-leetcode-extension/issues/6, and https://github.com/The-CodingSloth/haha-funny-leetcode-extension/issues/14.

**Comment by The-CodingSloth** [comment]
bro this is amazing, I didn't know this existed. I'll definitely check it out and see if I can migrate it to make the development experience better. If someone else wants to try as well feel free this is so cool.

**Comment by Walter-0** [comment]
I just discovered it too, and I was surprised at how sophisticated it seems.

**Comment by abbas-dhd** [comment]
even extension has its own framework 😲

**Comment by The-CodingSloth** [comment]
Just made the change to it's own branch, seems to work, but I'd appreciate if you guys could test it out
