### ISSUE TITLE
Bug: userJustSubmitted race condition

### ISSUE THREAD

**Issue by Erik-McKelvey** [The-CodingSloth/haha-funny-leetcode-extension#28]
The timeout in the onMessageReceived function in backjground.js introduces a race condition if the user hits submit more than once within 30 seconds:
```js
case 'userClickedSubmit':
  userJustSubmitted = true;
  setTimeout(() => {
    userJustSubmitted = false;
  }, 30000); // Reset after 30 seconds
  break;
```

I can fix it

**Comment by The-CodingSloth** [comment]
sweet sounds good thanks for noticing
