### ISSUE TITLE
The feature to select from JSON files (select which problem sets you want)

### ISSUE THREAD

**Issue by The-CodingSloth** [The-CodingSloth/haha-funny-leetcode-extension#3]
By default right now, the extension is using the Blind 75 problem set since that JSON file is hard coded in.
Need to modify it to let users pick which problem sets they want.
Some things to think about:
1. When the user installs the extension, do they have to select their problem set first or just give them a randomly problem and then decide?
2.  Allow the user to change their problem set before the 24 hours are up or allow them to change it, and it will apply tomorrow?

**Comment by slav-getov** [comment]
My 2 cents: Most probably the users will not be 'in the know' of the difference between the questions in blind75 and other categories. For your first question I would say - give them a random problem and then decide.
