### ISSUE TITLE
Add funny messages depending on the users submission of language.

### ISSUE THREAD

**Issue by The-CodingSloth** [The-CodingSloth/haha-funny-leetcode-extension#32]
Add some funny messages to the congratulationModal based on the programming language they used. You guys can come up with the messages.
Mainly just need to modify the checkIfUserSolvedProblem function to now use the data.lang to modify the message.

**Comment by harsh11101** [comment]
Hey @The-CodingSloth 
I would like to give this a go, this seems intresting. Also, great project can really help people. I hope it gets bigger.

**Comment by The-CodingSloth** [comment]
Thanks so much, I hope so too haha. Have fun with this

**Comment by harsh11101** [comment]
Hey @The-CodingSloth , everything is done, any suggestions for messages?

**Comment by The-CodingSloth** [comment]
uhhh I think it'd be funny for people who use languages like C++, Rust, and all that to get messages like "You think you're better than other people?" or like "Why would you use that for leetcode problems?" But if you have those types of messages set, then feel free to create the PR.
