### ISSUE TITLE
the redirect rule does not work on firefox

### ISSUE THREAD

**Issue by The-CodingSloth** [The-CodingSloth/haha-funny-leetcode-extension#34]
Was working on trying to get it to work on firefox, and have this issue:
``` javascript
async function setRedirectRule(newRedirectUrl: string) {
  let newRedirectRule = {
    id: RULE_ID,
    priority: 1,
    action: {
      type: "redirect",
      redirect: { url: newRedirectUrl }
    },
    condition: {
      urlFilter: "*://*/*",
      excludedInitiatorDomains: [
        "leetcode.com",
        "www.leetcode.com",
        "developer.chrome.com"
      ],

      resourceTypes: ["main_frame"]
    }
  }

  try {
    chrome.declarativeNetRequest.updateDynamicRules({
      removeRuleIds: [RULE_ID],
      addRules: [newRedirectRule]
    })
    const currentRules = await chrome.declarativeNetRequest.getDynamicRules()
    console.log("Redirect rule updated")
    console.log("Current rules:", currentRules)
  } catch (error) {
    console.error("Error updating redirect rule:", error)
  }
}
```
For some reason the new rule gets updated in chrome, but not in firefox. When I console log currentRules it shows an empty array on firefox, when it should be showing the rule inside of the array. If anyone knows why or can fix this, that'd be awesome and you're better than me

**Comment by green1490** [comment]
There is 2 possible case here. The first is that there is no active rule or you are using the [wrong object](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest/getDynamicRules).

**Comment by The-CodingSloth** [comment]
hmmm, I'm just having general problems using this on firefox for some reason the chrome.runtime.getURL works, the storage works, opening a new tab works, but some of the other chrome listeners like onCompleted and this declartiveNetRequest aren't. Might be an issue with this framework or I'm just dumb. They say using the chrome APIs should also work on firefox with their framework.

**Comment by green1490** [comment]
Are you giving them the proper [permissions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest) in your manifest.json?

**Comment by The-CodingSloth** [comment]
Yeah I think so, I'm gonna open a new branch for this if anyone wants to figure this out or see what's going on.

**Comment by green1490** [comment]
![image](https://github.com/The-CodingSloth/haha-funny-leetcode-extension/assets/46134377/54782807-1a77-4bf9-9104-4250c6c6d297)

**Comment by The-CodingSloth** [comment]
LOL whoops
