### ISSUE TITLE
Bug: Extension doesn't detect problem is solved

### ISSUE THREAD

**Issue by morenoh149** [The-CodingSloth/haha-funny-leetcode-extension#52]
I am using the new leetcode dynamic UI. (https://leetcode.com/discuss/feedback/4041069/Feedback%3A-Dynamic-Layout-is-technically-impressive-but-poor-design-and-UX.)

And now when I solve the leetcode gulag extension problem of the day the extension does not let me browse the internet.

Browser: Brave browser

Edit: I tried the extension again and I don't think the bug is related to the new Leetcode UX.

**Comment by The-CodingSloth** [comment]
Uploaded a new version to the public webstore with some small changes that should be coming in a few days. Let me know if that issue still happens when its public, or clone this repo to test it out right now. I've seen this happen sometimes, but I'm not too sure myself. Hopefully this minimizes/removes this bug.

**Comment by IlyaBaksonyan** [comment]
still happening

https://youtu.be/Ot8Be4OPh6M

**Comment by The-CodingSloth** [comment]
hmmm I'm not sure why this happens only sometimes. I'm curious if anyone can figure out where it's not working. It has to be in the checkIfUserSolvedProblem function in background.ts or the congratuationModal's handleClick function is not executing. I'll see if I can figure anything out. But if anyone wants to try it out too, feel free because I'm confused.

**Comment by The-CodingSloth** [comment]
I'd appreciate anyone that's contributing to provide some logs for the checkIfUserSolvedProblem function to see what's happening for these submissions that aren't being accepted.

**Comment by LucasJoel1** [comment]
Having this issue as well using brave, first issue is that brave seems to be denying it access to certain content the extension needs to work, to fix this, go to the extension settings and enable the setting that says Allow access to file urls,  second on in the console in dev to
![Screenshot 2023-09-17 174206](https://github.com/The-CodingSloth/haha-funny-leetcode-extension/assets/81326116/86e49aa6-a623-4db2-b5f8-436502005bf9)
ols, it is stating:

**Comment by The-CodingSloth** [comment]
I added a possible fix, no clue if that really worked. I tested it on Chrome and Brave and seemed to work. Added small console messages too when submitting. Let me know if that worked on the development build.

**Comment by LucasJoel1** [comment]
Hey, tried to load the extension from the repo to test but it doesn't have a manifest.json, would I be able to just use a basic one or are there certain scopes you are using.

**Comment by LucasJoel1** [comment]
That does not appear to have fixed the problem.  No errors have shown up in the console and I have given it all permissions.  If there is a logs file I can send you, please let me know so I can do so

**Comment by Tayomide** [comment]
I just checked it, the development code works fine, but the extension on the web store does not

**Comment by The-CodingSloth** [comment]
hmmm that's interesting can you screenshot the logs or drag them into this discussion. Some people have this issue and some don't, really has me confused lmao

**Comment by Tayomide** [comment]
Here's a Vimeo link showing the issue https://vimeo.com/865414717/2d6403a421

There are also no logs for the extension on the web store, maybe removing the logs also removed an important logic with it

**Comment by IlyaBaksonyan** [comment]
> hmmm that's interesting can you screenshot the logs or drag them into this discussion. Some people have this issue and some don't, really has me confused lmao

you're already immersed in the normal problems of business!

**Comment by The-CodingSloth** [comment]
> > hmmm that's interesting can you screenshot the logs or drag them into this discussion. Some people have this issue and some don't, really has me confused lmao
> 
> you're already immersed in the normal problems of business!

Yep already hate it lmao. So the web store version isn't working, but is this current development version working? If it is, I can publish this new version for now since it might minimize the problem

**Comment by IlyaBaksonyan** [comment]
> > > hmmm that's interesting can you screenshot the logs or drag them into this discussion. Some people have this issue and some don't, really has me confused lmao
> > 
> > 
> > you're already immersed in the normal problems of business!
> 
> Yep already hate it lmao. So the web store version isn't working, but is this current development version working? If it is, I can publish this new version for now since it might minimize the problem

but because of you I got into leetcode for the first time in 4 years and even already solved 5 problems.

**Comment by Tayomide** [comment]
Yeah, it does work👍

You could try creating sprints, goals to be accomplished at the end of the week and then do a code review before choosing to deploy the newest update to leetcode

I'm sure there are a lot of videos of that on YouTube, and GitHub has a Kanban board at the Projects tab
The main branch will only be updated after the code review, and maybe even write tests before the start of each week's sprint 
 and only accept code that passes the test

**Comment by The-CodingSloth** [comment]
Awesome, I think that's a pretty good idea to organize things a bit more and have proper version releases. I'll do research and see how I could do it. Would probably need to start by having important extension tests

**Comment by The-CodingSloth** [comment]
> > > > hmmm that's interesting can you screenshot the logs or drag them into this discussion. Some people have this issue and some don't, really has me confused lmao
> > > 
> > > 
> > > you're already immersed in the normal problems of business!
> > 
> > 
> > Yep already hate it lmao. So the web store version isn't working, but is this current development version working? If it is, I can publish this new version for now since it might minimize the problem
> 
> but because of you I got into leetcode for the first time in 4 years and even already solved 5 problems. And it seems like that I'm not the only one who did this.

Just wanted to say that's amazing. Did not expect this extension to actually be used, it was just a funny idea I had and wanted to try it out.

**Comment by Tayomide** [comment]
That would be cool! I'm looking forward to it! If it gets exhausting, you could move the sprints to more weeks, and GitHub actions could also help a lot with the automation of the tests! You'll basically be a project manager

**Comment by The-CodingSloth** [comment]
Apparently this bug is still happening, to the people that have had this bug.
can you let me know:
1. What problem set you used (all leetcode problems, neetcode 150, blind 75, etc)
2. The problem it was (if you remember) 
3. Browser you used.

**Comment by LucasJoel1** [comment]
Problem set used: All problems
Problem it was: Was issue with any problems as I unoaded and reloaded the extension giving me a new problem each time
Browser: Brave

**Comment by Private-programmer** [comment]
Hi, 

I had this issue as well. 

Problem set used: All problems
Problem it was: I don't remember (sorry 😔)
Browser: Chrome

Not sure if it will help but I also set the problem difficulty to easy.

**Comment by The-CodingSloth** [comment]
alright I just pushed a change in the code, can anyone test this out like a bunch of times. just resave the code to generate a new problem. I'm hoping this fixed it or i'm gonna go crazy, this bug is so rare, but it happens enough that it affects the torture experience.

**Comment by Tayomide** [comment]
The development code always worked for me, but the extension on chrome web store didn't

I'll check the new one out!

**Comment by The-CodingSloth** [comment]
yeah it took me like 30+ attempts to get it to happen and debug it, but when there's apparently 100s of users it was bound to happen to people (gotta love publicly used software)

**Comment by Tayomide** [comment]
On a side note could you walk me through setting up prettier? or that stuff you use to format the code, I tried setting it up but it never worked for me

Also, does it take a long time for the chrome web store to accept new updates?

**Comment by The-CodingSloth** [comment]
I'm just using the prettier extension from vs code, and prettier just automatically detects the file in codebase.
Also Chrome takes like 1-2 days to update the extension which is really annoying.
Side note:
if you guys haven't already should probably join the discord if you want to talk with me and other people, so we don't spam these discussions lmao:
Here's the link [Discord invite](https://discord.com/invite/2ByMHqTNca)

**Comment by Tayomide** [comment]
Thanks!

Done, I joined the discord!

I tried about 10 times, and there doesn't seem to be a problem with the dev code.

**Comment by The-CodingSloth** [comment]
people still had this problem, so I changed the logic a bit and it should've hopefully fixed it, if anybody can test it out for me I'd appreciate it

**Comment by Tayomide** [comment]
The recent changes have been updated on the extension, but it still doesn't work for me, I'll check if the new code in the repo works for me(it always has)

**Comment by The-CodingSloth** [comment]
LOL, I think this issue mainly happens in the build version when you run npm run build. It looked like a service worker issue when it became inactive, so when you're testing leave the extension and don't solve the problem until you see it say service worker inactive on the extension page.

**Comment by Tayomide** [comment]
Got it! I'll do that now👍

**Comment by shamir0xe** [comment]
I still have this issue, I solved more than 10 problems in order to get rid of the freaking tortures, but It's spread its webs over my throat. I forced to use safari instead of my dear Chrome, please ELP!

**Comment by Tayomide** [comment]
Hey!

Could you try this again? It works for me now

**Comment by morenoh149** [comment]
> Hey!
> 
> Could you reinstall the extension and try it again? It works for me now👌

Yeah I just tested it today and yesterday.

When I try to load a webpage I get directed to the gulag's problem of the day (potd). I then solve it but I'm still not allowed to open other websites.

When I click on the extension's icon in the toolbar and open the potd and then resubmit my solution then I can browse freely.

**Comment by Tayomide** [comment]
Dang💔
That's next-level torture
Maybe there'll be a week where we just upgrade this extension
You could also get your hands dirty if you have some time on you
Good luck!

**Comment by shamir0xe** [comment]
> Hey!
> 
> Could you reinstall the extension and try it again? It works for me now👌

I did reinstall it but It doesn't work still :(

**Comment by shamir0xe** [comment]
I solved the issue by disabling CORS with an [ALLOW CORS extension](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf). It should be fixed by setting the origin header tag to some requests in the code instead of allowing CORS globally (something like this: "Access-Control-Allow-Origin: *"). cheers!

**Comment by shamir0xe** [comment]
I solved the issue by disabling CORS with an [ALLOW CORS](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf) extension. It should be fixed by setting the origin header of some requests in the code instead of disabling the CORS globally (something like this: "Access-Control-Allow-Origin: *"). Cheers!

**Comment by morenoh149** [comment]
I'm still testing this. lmk if you want me to make a fresh issue.

My current issue is that

1. I try to browse the internet and am redirected to potd
2. I solve the problem after clicking around on the site, maybe reading the discussion and browsing devdocs.io (I always have the docs open in another tab)
3. I then reopen the potd from the extensions icon in the browser
4. I resubmit my solution to potd
5. Now I can browse freely.

**Comment by Tayomide** [comment]
Oh, I think it works perfectly for you!
You could go to the settings tab to change the difficulty or change the problem set you get your question from using the dropdown but that was coding sloth's actual plan of the extension, it's torture😎

**Comment by morenoh149** [comment]
@Tayomide so we're supposed to reopen the potd? why can't the extension detect you solved the problem the first time you open leetcode that day?

**Comment by SmokeShine** [comment]
I switched to new layout and it works now
