### ISSUE TITLE
The extension blocks you from practicing

### ISSUE THREAD

**Issue by KadirFrog** [The-CodingSloth/haha-funny-leetcode-extension#60]
# Problem (Unoptimal Situation)
If I want to practice leetcode and go to neetcode.io or search leetcode myself the extension still redirects me to the solving page. 
# Idea
Make the extension look for leetcode-based searches using open-ais API. 
[https://platform.openai.com/docs/api-reference/introduction](url)

**Comment by The-CodingSloth** [comment]
I appreciate the idea, but the purpose of the extension is to not let you go anywhere till you solve the problem that's where the torture in the name comes in (no google, no neetcode, no procrastination).  Solve your problem and you're free to do whatever again. 
When it comes to the openai idea.  
This project isn't making any money, and I'm not rich, so if we use openai in this project I'd probably go homeless.
Even with free alternatives, I don't need it would be worth it, but I could be wrong.
