### ISSUE TITLE
Sqrt(x) URL not updated in extension

### ISSUE THREAD

**Issue by 20kaushik02** [The-CodingSloth/haha-funny-leetcode-extension#88]
The URL to the problem is correct here:

https://github.com/The-CodingSloth/haha-funny-leetcode-extension/blob/a8ca8de1abf3899a8bcde9e7183fd79068ef3724/leetcode-problems/allProblems.json#L816

But the extension doesn't seem to be updated with the correct URL:

![image](https://github.com/The-CodingSloth/haha-funny-leetcode-extension/assets/59662438/31b17a7a-016f-4a82-94f2-eff6148d9439)

Please fix with an updated build :)

**Comment by Tayomide** [comment]
Hey!

Could you tell me your problem set? Thanks!

**Comment by 20kaushik02** [comment]
> Hey!
> 
> Could you tell me your problem set? Thanks!

It's "Top Interview Questions"
