### ISSUE TITLE
feat: add "Hyper Torture" mode

### ISSUE THREAD

**Issue by bukomp** [The-CodingSloth/haha-funny-leetcode-extension#89]
# ❗Hyper 🤓 Torture mode active❗

___"Infinite loop of despair activated."___

"Hyper Torture" mode is like the ultimate test for your brain while browsing the web. Turn it on, and **every** new website you visit brings up a random LeetCode problem. You're stuck there until you solve it! And guess what? Open another webpage, and _boom_, a new problem appears. This loop of challenges won’t stop until you turn off Hyper Torture mode.

But there's more! It counts your winning streak but be careful. It is in Sudden Death Mode. You make a mistake - your streak goes back to zero. It's all about keeping you on your toes and making sure you think hard before you code. Turn it on and off in the settings as you like. Are you ready for the challenge? #HyperTortureChallenge #BrainInPain

### How to Toggle On/Off Hyper Torture Mode:

1. **To Turn On:**
   - Go to the settings menu of the extension.
   - Find and click on the "Hyper Torture" mode option to activate it.

2. **To Turn Off:**
   - If you feel like tapping out, head back to the settings menu.
   - Click on the "Hyper Torture" mode option again to deactivate it.

### What is Hyper Torture:
- Task on New URL:
  - __Every time__ a new URL is opened, a random LeetCode problem pops up.
  - You cannot navigate the web freely until you solve the presented task.
  - This feature ensures that you are constantly torturing yourself and improving your problem-solving skills.
- Dedicated Streak Counter:
  - The Hyper Torture mode has its own streak counter.
  - The streak updates only when the Hyper Torture mode is enabled.
  - Your streak begins when you toggle on the mode and ends when you disable it from the settings.
- Sudden Death Mode:
  - A single wrong answer will reset your streak to zero.
  - This feature adds extra pressure and encourages careful and thoughtful coding.

**Comment by The-CodingSloth** [comment]
haha this is awesome, go crazy and have fun with it
